version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: ${PG_DATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:${PG_DATA}
  api:
    container_name: api
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
networks:
  webnet:
    driver: bridge
volumes:
  pgdata:
